language: node_js
node_js:
  - "0.10"
script: "npm run-script test-coverage"
after_script: "cat ./coverage/lcov.info | coveralls"
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/7cb74ac73beed6018dac
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

